export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FILTER_CATEGORY = "FILTER_CATEGORY";
export const FILTER_PRICE = "FILTER_PRICE";
export const FILTER_SORT = "FILTER_SORT";


